on:
  push:
    tags: 'v*'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: sad
          homebrew-tap: jswny/homebrew-test
          base-branch: master
          download-url: https://github.com/jswny/sad/archive/v3.0.1.tar.gz
          commit-message: Bump {{formulaName}} formula to {{version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}

