on: [push]

jobs:
  notify:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Output
        run: |
          echo ${{ github.ref }}
