on: [push]

jobs:
  run:
    name: Run Action
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run
        id: run
        uses: ./
        with:
          who-to-greet: "Mona the Octocat"
      - name: Get Time
        run: echo "The time was ${{ steps.run.outputs.time }}"
